### ISSUE TITLE
RFE - add option to configure hostname in cloud-init

### ISSUE THREAD

**Issue by jduncan-rva** [c0dyhi11/ubuntu-20-04-autoinstall#3]
as cheap as 4/8GB USB sticks are, each node can have one with their hostname, etc. set. Toss in a sticky DHCP lease and you're off to the races with DNS and everything else.

**Comment by c0dyhi11** [comment]
@jduncan-rva 
```bash
git pull
git checkout add-hostname
```

Then you should be able to test this new setting. 
Let me know if it works in #4
